[kafka]
k1 ansible_host=10.0.0.1 node_id=1
k2 ansible_host=10.0.0.2 node_id=2
k3 ansible_host=10.0.0.3 node_id=3

[envoy]
e1 ansible_host=10.0.0.10 priority=110
e2 ansible_host=10.0.0.11 priority=100

[all:vars]
vip=10.0.0.100
domain=kafka.bank.example.com
