security.protocol=SSL
ssl.truststore.type=PEM
ssl.truststore.location=/certs/ca.crt
ssl.keystore.type=PEM
ssl.keystore.location=/certs/client.pem
# Disable hostname verification inside Docker (envoy hostname resolves correctly)
ssl.endpoint.identification.algorithm=
